### ISSUE TITLE
Incorrect use for OneDrive redirected folders

### ISSUE THREAD

**Issue by kilasuit** [jdhitsolutions/MyTasks#35]
The use within line 
https://github.com/jdhitsolutions/MyTasks/blob/f46435fc7591ebe4ce141538568e68e710fe715f/MyTasks.psm1#L9

when using OneDrive folders or redirected folders will not correctly resolve

This should be changed to 

`[Environment]::GetFolderPath([Environment+SpecialFolder]::MyDocuments)`

which will call the correct registry path to get the correct path for the Documents folder

You can also see other special paths too via the below

![image](https://user-images.githubusercontent.com/6355225/53089517-b8517c00-3504-11e9-90d5-761279274d57.png)

**Comment by thecliguy** [comment]
This presents an issue for me too...

I am running PowerShell 5.1.16299.461 on Windows 10 (1709) in a domain environment where documents are redirected to a network share via a GPO.

Consequently `"$home\Documents"` is inappropriate because `$home` points to `C:\Users\<USERNAME>` instead of the UNC path of the network share.

The only reason I discovered this because in my case due to the use of redirection there is no `Documents` subdirectory off of `C:\Users\<USERNAME>`, which results in an error when generating the XML file:
![image](https://user-images.githubusercontent.com/23440389/53092016-7d9f1200-350b-11e9-81d4-17673993a4ce.png)

I have tested the suggested fix of using `[Environment]::GetFolderPath([Environment+SpecialFolder]::MyDocuments)` and can confirm that it does resolve to the appropriate location for me.

**Comment by jdhitsolutions** [comment]
As I do more cross-platform scripting I'm realizing the limitations of using built in variables and providers.  But in this case using the [environment] class makes much more sense.

**Comment by jdhitsolutions** [comment]
This has been addressed in v2.0.0 which is now in the PowerShell Gallery.

**Comment by kilasuit** [comment]
Closing as now fixed
