### ISSUE TITLE
Priority Field

### ISSUE THREAD

**Issue by Beetleman76** [jdhitsolutions/MyTasks#9]
Would it be possible to add a "Priority" field?  Possibly use a numbering system (1-10) and then being able to sort via due date and priority?

Thanks for this script, it is handy.

**Comment by jdhitsolutions** [comment]
That is certainly a reasonable request. You could use the Description property to record priority.  If I add it I probably wouldn't make it part of the default output, but I could build a custom view or perhaps add a parameter to Get-MyTask.

Anyone else care to voice an opinion on this?

**Comment by dft277** [comment]
I could see value in that especially if there were a Show-Task option to sort by priority.   The nifty colorized feature of Show-Task lets me see what's overdue so it would be feasible to replace the OverDue column and maintain the same output size.

**Comment by jdhitsolutions** [comment]
I know it has been awhile since I looked at this. I'm wondering if we could just use the category field. You could add whatever priority you wanted. That way people can define "priority" the way they need. You may want a 1-10 value, someone else may want 1-5. And which means "higher"? 1 or 10? What if you want High, Medium and Low? I'm liking the idea of using category for this.

**Comment by jdhitsolutions** [comment]
I don't think I am going to address this by expanding the object. The category value should be used.
